# config/cable.yml
development:
  adapter: 
  # url: redis://localhost:6379/1
  channel_prefix: mafl_development

test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  channel_prefix: mafl_api_production