# config/cable.yml
development:
  adapter: async
  # url: redis://localhost:6379/1
  channel_prefix: mafl_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: mafl_production