
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: mafl_api_development
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USER", "mafl_api_user") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "M@fl1Logistics") %>
    migrations_paths: db/migrate
  cache:
    <<: *default
    database: mafl_api_development
    schema_search_path: cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: mafl_api_development
    schema_search_path: queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: mafl_api_development
    schema_search_path: cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: mafl_api_test
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USER", "mafl_api_user") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "M@fl1Logistics") %>
    migrations_paths: db/migrate
  cache:
    <<: *default
    database: mafl_api_test
    schema_search_path: cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: mafl_api_test
    schema_search_path: queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: mafl_api_test
    schema_search_path: cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/migrate
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_search_path: cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_search_path: queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_search_path: cable
    migrations_paths: db/cable_migrate
